[Reading 23 lines from start (total: 23 lines, 0 remaining)]

const OIDC="https://mcp.pravidhisolutions.in/auth/realms/pravidhi";
const CLIENT_ID="https://mcp.pravidhisolutions.in/dashboard/client.json";
const REDIRECT=location.origin+"/dashboard/callback";
const SCOPE="openid profile email offline_access pravidhi.read";
const $=s=>document.querySelector(s);
function b64(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function challenge(v){return b64(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v)))}
function token(){return sessionStorage.getItem("access_token")||""}
function clearTokens(){["access_token","refresh_token","expires_at","oauth_state","oauth_verifier"].forEach(k=>sessionStorage.removeItem(k))}
function saveTokens(d){sessionStorage.setItem("access_token",d.access_token);if(d.refresh_token)sessionStorage.setItem("refresh_token",d.refresh_token);sessionStorage.setItem("expires_at",String(Date.now()+((d.expires_in||300)-20)*1000))}
async function refresh(){const r=sessionStorage.getItem("refresh_token");if(!r)return false;const body=new URLSearchParams({grant_type:"refresh_token",client_id:CLIENT_ID,refresh_token:r});const x=await fetch(OIDC+"/protocol/openid-connect/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});if(!x.ok){clearTokens();return false}saveTokens(await x.json());return true}
async function api(path){if(!token()||Date.now()>Number(sessionStorage.getItem("expires_at")||0)){if(!await refresh())throw new Error("auth")}let r=await fetch("/dashboard/api/"+path,{headers:{Authorization:"Bearer "+token(),Accept:"application/json"}});if(r.status===401&&await refresh())r=await fetch("/dashboard/api/"+path,{headers:{Authorization:"Bearer "+token(),Accept:"application/json"}});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||"request_failed");return r.json()}
async function login(){const verifier=b64(crypto.getRandomValues(new Uint8Array(32))),state=b64(crypto.getRandomValues(new Uint8Array(24))),ch=await challenge(verifier);sessionStorage.setItem("oauth_verifier",verifier);sessionStorage.setItem("oauth_state",state);const q=new URLSearchParams({client_id:CLIENT_ID,redirect_uri:REDIRECT,response_type:"code",scope:SCOPE,state,code_challenge:ch,code_challenge_method:"S256",resource:"https://mcp.pravidhisolutions.in"});location.href=OIDC+"/protocol/openid-connect/auth?"+q}
async function callback(){const q=new URLSearchParams(location.search),code=q.get("code"),state=q.get("state");if(!code)return false;if(state!==sessionStorage.getItem("oauth_state"))throw new Error("oauth_state_mismatch");const body=new URLSearchParams({grant_type:"authorization_code",client_id:CLIENT_ID,redirect_uri:REDIRECT,code,code_verifier:sessionStorage.getItem("oauth_verifier")});const r=await fetch(OIDC+"/protocol/openid-connect/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});if(!r.ok)throw new Error("oauth_token_exchange_failed");saveTokens(await r.json());history.replaceState({},document.title,"/dashboard/#devices");return true}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function loginView(msg){$("#app").innerHTML='<div class="page"><div class="login card"><div class="logo">⌘</div><h1 class="title">Pravidh Commander</h1><p>Remote MCP access to your authorized machines. Sign in through the Pravidh identity service to view devices and usage.</p>'+(msg?'<div class="error">'+esc(msg)+"</div>":"")+'<button class="btn" id="login">Sign in with Pravidh</button></div></div>';$("#login").onclick=login}
async function devices(){const d=await api("devices"),list=d.agents||[];let rows=list.map(a=>'<div class="device"><div class="device-left"><div class="device-icon">▣</div><div><div class="device-name">'+esc(a.name)+'</div><div class="meta">'+esc(a.platform)+' · '+esc(a.version||"agent")+' · Last seen '+(a.last_seen_at?new Date(a.last_seen_at).toLocaleString():"never")+'</div></div></div><div class="status"><i class="dot '+(a.status==="online"?"online":"")+'"></i>'+esc(a.status)+'</div></div>').join("");if(!rows)rows='<div class="device"><div><div class="device-name">No devices paired</div><div class="meta">Connect a machine below to begin.</div></div></div>';return '<div class="page"><div class="eyebrow">REMOTE MCP</div><h1 class="title">Devices</h1><p class="sub">Machines your AI clients can reach through Pravidh Remote MCP.</p><div class="card">'+rows+'</div><div class="connect card"><h3>Where you use it</h3><p>Install the Pravidh endpoint agent on a machine you own, then connect any compatible MCP client to the same tunnel.</p><div class="code">Pravidh agent installation is available from the secure pairing flow.</div><div style="margin-top:14px"><a class="btn secondary" href="https://mcp.pravidhisolutions.in/mcp">MCP endpoint</a></div></div></div>'}
async function usage(){const d=await api("usage"),pct=Math.min(100,d.calls/d.limit*100);return '<div class="page"><div class="eyebrow">ACCOUNT</div><h1 class="title">Usage</h1><p class="sub">Current-month activity for your Pravidh Remote MCP account.</p><div class="grid"><div class="metric card"><div class="label">Tool calls</div><div class="value">'+d.calls+'</div><div class="hint">of '+d.limit.toLocaleString()+' monthly allowance</div><div class="progress"><i style="width:'+pct+'%"></i></div></div><div class="metric card"><div class="label">Devices</div><div class="value">'+d.devices+'</div><div class="hint">registered endpoints</div></div><div class="metric card"><div class="label">Audit events</div><div class="value">'+d.auditEvents+'</div><div class="hint">current month</div></div></div></div>'}
async function billing(){const d=await api("billing");return '<div class="page"><div class="eyebrow">ACCOUNT</div><h1 class="title">Plan & billing</h1><p class="sub">Manage the commercial layer of Pravidh Remote MCP.</p><div class="plan card"><div><div class="eyebrow">CURRENT PLAN</div><h2 style="margin:6px 0">'+esc(d.plan)+'</h2><div class="meta">'+esc(d.status)+'</div></div><span class="badge">'+esc(d.badge)+'</span></div><div class="connect card"><h3>Billing integration</h3><p>'+esc(d.message)+'</p><a class="btn secondary" href="https://store.pravidhisolutions.in/products">View Pravidh products</a></div></div>'}
async function settings(){const d=await api("settings");return '<div class="page"><div class="eyebrow">ACCOUNT</div><h1 class="title">Settings</h1><p class="sub">Identity and connection settings for Pravidh Remote MCP.</p><div class="card"><div class="setting"><b>Account</b><span>'+esc(d.email||d.username||d.subject)+'</span></div><div class="setting"><b>Tenant</b><span>'+esc(d.tenant)+'</span></div><div class="setting"><b>MCP endpoint</b><span>https://mcp.pravidhisolutions.in/mcp</span></div><div class="setting"><b>Authorization server</b><span>'+esc(OIDC)+'</span></div><div class="setting"><b>Granted scope</b><span>pravidhi.read</span></div></div></div>'}
async function route(){const page=(location.hash||"#devices").slice(1);document.querySelectorAll(".nav").forEach(a=>a.classList.toggle("active",a.dataset.page===page));try{$("#app").innerHTML=page==="devices"?await devices():page==="usage"?await usage():page==="billing"?await billing():await settings();const me=await api("me");$("#account").textContent=me.email||me.username||"Pravidh account"}catch(e){if(e.message==="auth")loginView("");else $("#app").innerHTML='<div class="page"><div class="error">Unable to load dashboard: '+esc(e.message)+'</div></div>'}}
async function start(){try{await callback()}catch(e){clearTokens();loginView(e.message);return}if(!token()){loginView("");return}route()}
window.addEventListener("hashchange",route);window.addEventListener("load",start);

[executed on device: srv1726408 (3f3dbd4c-7c2a-40c6-a412-01d90ebec96d)]